---
abstract: 'run perltidy and podtidy before Git commits'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  FindBin: '0'
  Path::Tiny: '0'
  Sys::Cmd: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::TempDir::Tiny: '0'
  Time::Piece: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
  Path::Tiny: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-githook-perltidy
no_index:
  directory:
    - t
    - inc
  package:
    - App::githook::perltidy::install
    - App::githook::perltidy::install_CI
    - App::githook::perltidy::pre_commit
    - App::githook::perltidy::pre_commit_CI
    - App::githook::perltidy_CI
requires:
  Carp: '0'
  File::Basename: '0'
  OptArgs2: v2.0.0
  Path::Tiny: '0'
  Perl::Tidy: '0'
  Pod::Text: '0'
  Pod::Tidy: '0'
resources:
  repository: ssh://git@github.com/mlawren/githook-perltidy.git
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
